### ISSUE TITLE
[Issue]: SD3 cpp implementation build on WIndows issue

### ISSUE THREAD

**Issue by Jay19751103** [ROCm/llvm-project#114]
### Problem Description

I try to build sd3 cpp implementation from
https://github.com/leejet/stable-diffusion.cpp

Linux can build and run. but using HIPSDK on windows. 
I get the error

cmake .. -G "Ninja" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DSD_HIPBLAS=ON -DCMAKE_BUILD_TYPE=Release -DAMDGPU_TARGETS=gfx1100

LINK : warning LNK4044: unrecognized option '/v'; ignored
LINK : warning LNK4001: no object files specified; libraries used
LINK : warning LNK4068: /MACHINE not specified; defaulting to X64
LINK : fatal error LNK1561: entry point must be defined

This looks related with -v option in ggml\src\CMakeLists.txt
The line 
COMMAND ${CMAKE_C_COMPILER} ${CMAKE_EXE_LINKER_FLAGS} -Wl,-v

The linux can pass the configuration

Anyone can help to solve this 

### Operating System

Windows 11 Pro 23H2

### CPU

AMD 7700X

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 5.7.1, ROCm 5.7.0

### Steps to Reproduce

following the stable diffusion cpp's get source and build guide with preinstalled HIPSDK 5.7 (5.5 also have same issue)

**Comment by ppanchad-amd** [comment]
@Jay19751103 Internal ticket has been created to fix this issue. Thanks!

**Comment by schung-amd** [comment]
Hi @Jay19751103, are you still experiencing this issue? I am unable to reproduce the issue with the latest version of the HIP SDK (6.1 at the time of writing), following the guide at https://github.com/leejet/stable-diffusion.cpp/blob/master/docs%2FhipBLAS_on_Windows.md and additionally installing Strawberry Perl as Perl does not ship with Windows.
