### ISSUE TITLE
[COMGR] Codegen is slow.

### ISSUE THREAD

**Issue by lshqqytiger** [ROCm/llvm-project#116]
### Suggestion Description

`AMD_COMGR_ACTION_CODEGEN_BC_TO_RELOCATABLE` takes lots of time than other tasks.
It depends on the input and environment, but it is hard to accept considering system configuration.
(I assume it is single thread)
The best: 1\~2s
Most cases: 20\~30s or 60\~70s
The worst: 80\~100s

Is there any way to make it faster?

maybe related: #36

#### HIP SDK version
6.1.40252-53f3e11ac (official AMD release)

#### CPU
Intel Core i9 14900K

### Operating System

Windows 11 Pro

### GPU

RX 7900 XTX

### ROCm Component

COMGR

**Comment by lamb-j** [comment]
@lshqqytiger Are you getting between 1 and 100 seconds when using Comgr to Codegen the same bitcode? Or different execution times for different bitcodes?

The size of the bitcode passed to the Codegen action will impact the length of time taken for the compilation.

Can you provide a simple reproducer that's calling AMD_COMGR_ACTION_CODEGEN_BC_TO_RELOCATABLE on your bc file?

**Comment by lamb-j** [comment]
This is a probably general LLVM/clang issue, and not anything specific to Comgr or ROCm LLVM.

I'd assume if you tried the same compilation with upstream clang you'd see similar results.

That said, we do have some work in progress that will hopefully result in long-term improvements for compilation time, especially for large files.
