### ISSUE TITLE
[Issue]: Create 6.1.x branch

### ISSUE THREAD

**Issue by torrance** [ROCm/llvm-project#82]
### Problem Description

As per the [build guide for NVIDIA](https://rocm.docs.amd.com/projects/HIP/en/latest/developer_guide/build.html) systems, I need to check out the `$ROCM_BRANCH` branch of hipcc.git. e.g.:

```
      export ROCM_BRANCH=rocm-6.1.x
      git clone -b "$ROCM_BRANCH" https://github.com/ROCm-Developer-Tools/hip.git
      git clone -b "$ROCM_BRANCH" https://github.com/ROCm-Developer-Tools/clr.git
      git clone -b "$ROCM_BRANCH" https://github.com/ROCm-Developer-Tools/HIPCC.git
      git clone -b "$ROCM_BRANCH" https://github.com/ROCm/hipother.git
```

Currently, however, whilst `rocm-6.1.x` exists in the other repos, I am forced to check out the `rocm-6.0.x` branch for HIPCC as this is the latest existing branch.

(Note also the documentation entirely fails to mention the `hipother.git` branch.)

Please either create a branch to allow consistency in building for NVIDIA or update the build instructions for NVIDIA systems to reflect the correct process.

### Operating System

n/a

### CPU

n/a

### GPU

AMD Instinct MI250X

### ROCm Version

ROCm 6.1.0

**Comment by lamb-j** [comment]
See updated instructions here: https://github.com/ROCm/HIP/blob/develop/docs/install/build.rst

We're working on updating https://rocm.docs.amd.com/projects/HIP/en/latest/install/build.html to reflect these changes as well.

HIPCC was used to set the HIP_PLATFORM if none was provided. However, if you provide HIP_PLATFORM=amd|nvidia to cmake, you can omit the HIPCC build and paths

**Comment by lamb-j** [comment]
Thanks again for bringing this up!

See updated instructions here [https://rocm.docs.amd.com/projects/HIP/en/latest/install/build.html](https://rocm.docs.amd.com/projects/HIP/en/latest/install/build.html)
