### ISSUE TITLE
[Issue]: comgr fails to build hip code on musl systems

### ISSUE THREAD

**Issue by AngryLoki** [ROCm/llvm-project#92]
### Problem Description

While running amd/comgr autotests with musl libc, tests related to HIP code fail like this:
```
33/38 Test: comgr_compile_source_to_executable
Command: "/var/tmp/portage/dev-libs/rocm-comgr-6.1.1/work/llvm-project-rocm-6.1.1/amd/comgr_build/test/compile_source_to_executable"
Directory: /var/tmp/portage/dev-libs/rocm-comgr-6.1.1/work/llvm-project-rocm-6.1.1/amd/comgr_build/test
"comgr_compile_source_to_executable" start time: May 22 04:02 UTC
Output:
----------------------------------------------------------
In file included from <built-in>:1:
In file included from /usr/lib/llvm/18/bin/../../../../lib/clang/18/include/__clang_hip_runtime_wrapper.h:111:
/usr/lib/llvm/18/bin/../../../../lib/clang/18/include/cuda_wrappers/cmath:27:15: fatal error: 'cmath' file not found
   27 | #include_next <cmath>
      |               ^~~~~~~
1 error generated when compiling for gfx900.
FAILED: amd_comgr_do_action
 REASON: ERROR
<end of output>
Test time =   0.74 sec
----------------------------------------------------------
Test Failed.
```

Note, that clang and hipcc work, this is just an issue of comgr runtime compiler.

The problem is caused by lines https://github.com/ROCm/llvm-project/blob/rocm-6.1.1/amd/comgr/src/comgr-compiler.cpp#L1054-L1055
```
    Args.push_back("-target");
    Args.push_back("x86_64-unknown-linux-gnu");
```

The correct target would be `x86_64-unknown-linux-musl`, however the easiest fix is just to remove these 2 lines, because clang uses host target by default. Removing these 2 lines allows all comgr tests to pass with musl libc (given that other non-musl fixes are applied and excluding comgr_nested_kernel_test due to https://github.com/ROCm/llvm-project/issues/35).

Not setting `-target` enables automatic target selection and setting up flags:
* glibc system automatically adds `/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/` to include path
* musl system automatically adds `/usr/lib/gcc/x86_64-gentoo-linux-musl/13/include/g++-v13/` to include path

### Operating System

Gentoo / musl profile

### CPU

-

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.1.0

**Comment by lamb-j** [comment]
Thanks for the suggestion!

Testing your suggested change internally, I'll report back with the results

**Comment by lamb-j** [comment]
Still testing the change removing these lines:

  Args.push_back("-target");
  Args.push_back("x86_64-unknown-linux-gnu");
    
 Initial tests removing those have broken some components relying on Comgr, like hipRTC. I'm looking into those failures now

**Comment by lamb-j** [comment]
https://github.com/ROCm/llvm-project/commit/9f0d1687aa6a5403acd0d6f8eafedb581e8e3c6f

Let me know if this doesn't fix your issue. Thanks again for the suggestion!
